helm:
  parameters:
    - repository: image.name
      value: 507325772667.dkr.ecr.ap-northeast-2.amazonaws.com/ca
      forcestring: true
    - name: image.tag
      value: "abc123"
      forcestring: true
