helm:
  parameters:
  - name: ""
    value: 507325772667.dkr.ecr.ap-northeast-2.amazonaws.com/ca
    forcestring: true
  - name: image.tag
    value: "257"
    forcestring: true
  - name: image.name
    value: 507325772667.dkr.ecr.ap-northeast-2.amazonaws.com/ca
    forcestring: true
