helm:
  parameters:
  - name: ""
    value: khabh/test
    forcestring: true
  - name: image.tag
    value: "134"
    forcestring: true
  - name: image.name
    value: khabh/test
    forcestring: true
