replicaCount: 1

image:
  repository: khabh/test         # ✅ 도커허브 사용자명/이미지명
  pullPolicy: IfNotPresent
  tag: ""                         # 또는 특정 태그: "v1.0.0"

imagePullSecrets: []             # 필요하면 설정

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080                     # ✅ Spring Boot 기본 포트

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: your-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 8080                   # ✅ 포트 이름 대신 숫자 포트로
readinessProbe:
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}