replicaCount: 1

image:
  repository: 507325772667.dkr.ecr.ap-northeast-2.amazonaws.com/ca        # ✅ 도커허브 사용자명/이미지명
  pullPolicy: IfNotPresent
  tag: "abc123"                         # 또는 특정 태그: "v1.0.0"

imagePullSecrets:
  - name: ecr-registry-secret # 필요하면 설정

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 30080 # ✅ Spring Boot 기본 포트

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: your-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 8080                   # ✅ 포트 이름 대신 숫자 포트로
readinessProbe:
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}